FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs

COPY . .
EXPOSE 8000
ENV FRONT_URL=http://localhost:5000

RUN npm install
CMD [ "npm", "start" ]

